# Configuration file for InSDN Traffic Analysis

# Data paths
data:
  raw_path: "data/raw"
  processed_path: "data/processed"
  
# Preprocessing parameters
preprocessing:
  remove_duplicates: true
  handle_missing: true
  outlier_threshold: 3.0
  
# Feature extraction
features:
  numerical_features:
    - "packet_length"
    - "flow_duration"
    - "packet_count"
  categorical_features:
    - "protocol"
    - "flow_type"
    
# LLM configuration
llm:
  model_name: "bert-base-uncased"  # Can be updated based on requirements
  max_length: 512
  batch_size: 32
  
# Agent parameters
agents:
  learning_rate: 0.001
  update_frequency: 100
  threshold: 0.8
  
# Visualization
visualization:
  update_interval: 5  # seconds
  max_points: 1000
  
# Logging
logging:
  level: "INFO"
  file_path: "experiments/logs"
  
# Monitoring
monitoring:
  metrics_port: 8000
  dashboard_port: 8050
